const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const devices_dep = b.dependency("devices", .{
        .target = target,
        .optimize = optimize,
    });
    const analysis_dep = b.dependency("analysis", .{
        .target = target,
        .optimize = optimize,
    });
    const solvers_dep = b.dependency("solvers", .{
        .target = target,
        .optimize = optimize,
    });
    const fastvaf_dep = b.dependency("fastvaf", .{
        .target = target,
        .optimize = optimize,
    });

    const exe = b.addExecutable(.{
        .name = "zpicey",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "devices", .module = devices_dep.module("devices") },
                .{ .name = "analysis", .module = analysis_dep.module("analysis") },
                .{ .name = "solvers", .module = solvers_dep.module("solvers") },
                .{ .name = "fastvaf", .module = fastvaf_dep.module("fastvaf") },
            },
        }),
    });
    exe.root_module.link_libc = true;
    b.installArtifact(exe);

    // Top-level tests: circuit construction (Builder) + every analysis
    // through the public module surface.
    const builder_mod = b.createModule(.{
        .root_source_file = b.path("src/builder.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "analysis", .module = analysis_dep.module("analysis") },
            .{ .name = "devices", .module = devices_dep.module("devices") },
        },
    });
    const tests_mod = b.createModule(.{
        .root_source_file = b.path("tests/test_all.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "analysis", .module = analysis_dep.module("analysis") },
            .{ .name = "devices", .module = devices_dep.module("devices") },
            .{ .name = "solvers", .module = solvers_dep.module("solvers") },
            .{ .name = "builder", .module = builder_mod },
        },
    });
    const tests = b.addTest(.{ .root_module = tests_mod });
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run top-level tests");
    test_step.dependOn(&run_tests.step);

    const run_step = b.step("run", "Run ZPicey");
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    run_step.dependOn(&run_cmd.step);

    // Benchmark harness
    const bench_runner = b.addExecutable(.{
        .name = "bench-runner",
        .root_module = b.createModule(.{
            .root_source_file = b.path("benchmark/src/runner.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    b.installArtifact(bench_runner);

    const run_bench = b.addRunArtifact(bench_runner);
    run_bench.step.dependOn(b.getInstallStep());
    run_bench.stdio = .inherit;
    run_bench.setCwd(b.path("."));
    run_bench.addArgs(&.{ "zig-out/bin/zpicey", "benchmark/fixtures" });
    if (b.args) |args| run_bench.addArgs(args);
    const bench_step = b.step("bench", "Run benchmarks");
    bench_step.dependOn(&run_bench.step);

    // -----------------------------------------------------------------------
    // GPU compute (phase 1): host runtime + PTX kernel pipeline + smoke test.
    // Nothing here touches the simulator; with -Dgpu=false (the default) the
    // main build graph is unchanged and test-gpu just prints "skipped".
    // -----------------------------------------------------------------------
    const gpu = b.option(bool, "gpu", "Build nvptx GPU kernels and enable the GPU smoke test") orelse false;
    const gpu_nv_arch = b.option([]const u8, "gpu-nv-arch", "NVIDIA SM architecture for PTX codegen") orelse "sm_89";

    const compute_dep = b.dependency("compute", .{
        .target = target,
        .optimize = optimize,
    });

    const gpu_opts = b.addOptions();
    gpu_opts.addOption(bool, "gpu", gpu);

    // Generated "kernels" module: one `pub const <name> = @embedFile("<name>.ptx")`
    // per kernel in modules/compute/kernels/, or empty stubs when -Dgpu=false so
    // the smoke test still compiles (and skips at runtime).
    const kernels_wf = b.addWriteFiles();
    var kernels_src: std.ArrayList(u8) = .empty;
    kernels_src.appendSlice(b.allocator, "//! Generated by build.zig — embedded PTX kernel images.\n") catch @panic("OOM");

    for (listKernels(b)) |name| {
        if (gpu) {
            const ptx = buildPtxKernel(b, name, gpu_nv_arch);
            _ = kernels_wf.addCopyFile(ptx, b.fmt("{s}.ptx", .{name}));
            kernels_src.appendSlice(b.allocator, b.fmt(
                "pub const {s} = @embedFile(\"{s}.ptx\");\n",
                .{ name, name },
            )) catch @panic("OOM");
        } else {
            kernels_src.appendSlice(b.allocator, b.fmt(
                "pub const {s} = \"\"; // -Dgpu=false: kernel not built\n",
                .{name},
            )) catch @panic("OOM");
        }
    }
    const kernels_root = kernels_wf.add("kernels.zig", kernels_src.items);
    const kernels_mod = b.createModule(.{
        .root_source_file = kernels_root,
        .target = target,
        .optimize = optimize,
    });

    // e2e smoke test: probe -> load PTX -> saxpy over 1M floats -> verify.
    const test_gpu_exe = b.addExecutable(.{
        .name = "test-gpu",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compute/tests/test_saxpy_e2e.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "compute", .module = compute_dep.module("compute") },
                .{ .name = "kernels", .module = kernels_mod },
                .{ .name = "gpu_config", .module = gpu_opts.createModule() },
            },
        }),
    });
    test_gpu_exe.root_module.link_libc = true;

    const run_test_gpu = b.addRunArtifact(test_gpu_exe);
    run_test_gpu.stdio = .inherit;
    b.step("test-gpu", "Run the GPU saxpy smoke test (skips cleanly without -Dgpu=true or a device)")
        .dependOn(&run_test_gpu.step);
}

/// Kernel sources are modules/compute/kernels/<name>.zig; each must export its
/// entry point(s) with the PTX-visible name(s) the host looks up.
fn listKernels(b: *std.Build) []const []const u8 {
    const io = b.graph.io;
    var names: std.ArrayList([]const u8) = .empty;
    var dir = b.build_root.handle.openDir(io, "modules/compute/kernels", .{ .iterate = true }) catch
        @panic("cannot open modules/compute/kernels");
    defer dir.close(io);
    var it = dir.iterate();
    while (it.next(io) catch @panic("cannot list modules/compute/kernels")) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;
        names.append(b.allocator, b.dupe(entry.name[0 .. entry.name.len - 4])) catch @panic("OOM");
    }
    std.mem.sort([]const u8, names.items, {}, struct {
        fn lt(_: void, a: []const u8, c: []const u8) bool {
            return std.mem.lessThan(u8, a, c);
        }
    }.lt);
    return names.items;
}

/// Zig 0.16's LLVM backend can't emit nvptx objects directly ("NVPTX aliasee
/// must be a non-kernel function definition"), so each kernel goes through:
///   1. zig build-obj -femit-llvm-ir   (kernel Zig -> LLVM IR)
///   2. ptx_rewrite                    (drop @export aliases, rename defines)
///   3. llc -march=nvptx64             (IR -> PTX text; llc from the dev shell)
fn buildPtxKernel(b: *std.Build, name: []const u8, nv_arch: []const u8) std.Build.LazyPath {
    const emit_ir = b.addSystemCommand(&.{
        b.graph.zig_exe,                "build-obj",
        "-target",                      "nvptx64-cuda-none",
        b.fmt("-mcpu={s}", .{nv_arch}), "-fno-emit-bin",
        "-fno-ubsan-rt",                "-fstrip",
        "-O",                           "ReleaseFast",
    });
    const ll = emit_ir.addPrefixedOutputFileArg("-femit-llvm-ir=", b.fmt("{s}.ll", .{name}));
    emit_ir.addFileArg(b.path(b.fmt("modules/compute/kernels/{s}.zig", .{name})));

    const rewrite_exe = b.addExecutable(.{
        .name = "ptx_rewrite",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compute/tools/ptx_rewrite.zig"),
            .target = b.graph.host,
            .optimize = .Debug,
        }),
    });
    const rewrite = b.addRunArtifact(rewrite_exe);
    rewrite.addFileArg(ll);
    const ll_fixed = rewrite.addOutputFileArg(b.fmt("{s}.fixed.ll", .{name}));

    const llc = b.addSystemCommand(&.{
        "llc",
        "-march=nvptx64",
        b.fmt("-mcpu={s}", .{nv_arch}),
        "-O3",
    });
    llc.addFileArg(ll_fixed);
    llc.addArg("-o");
    return llc.addOutputFileArg(b.fmt("{s}.ptx", .{name}));
}
