//! kernels.zig — the gompute-facing registration for BUILTIN device GPU kernels.
//! One raw kernel per eligible builtin device, generated by looping the auto
//! catalog at comptime. gompute's `emitKernels` (top-level build) recompiles
//! this with the device flag to bake PTX (NVIDIA) and AMDGCN (AMD) into the app.
//!
//! Dynamic `.so` devices are NOT here — they register their one device from the
//! SAME `engine.DeviceKernel` template at `.so`-build-time, so the format is
//! identical by construction.
//!
//! On the host pass (`is_device == false`) `exportRaw`/`globalIdX` are no-ops /
//! unreferenced, so this file compiles cleanly without a GPU.

const gompute = @import("gompute");
const engine = @import("engine.zig");
const models = @import("models");

/// Threads per block for device kernels. gompute launches ceil(count/block_size).
pub const block_size: u32 = 256;

/// Symbol prefix for a device's eval kernel — `arp_eval_<name>`. The host links
/// each builtin batch to its kernel by this name; a dynamic `.so` exports the
/// same-shaped symbol for its device.
pub fn kernelName(comptime name: []const u8) [:0]const u8 {
    return "arp_eval_" ++ name;
}

comptime {
    if (gompute.is_device) {
        for (@typeInfo(models).@"struct".decls) |d| {
            const D = @field(models, d.name);
            if (engine.gpuEligible(D)) {
                gompute.exportRaw(kernelName(d.name), &engine.DeviceKernel(D, block_size).run);
            }
        }
    }
    gompute.exportKernels(.{});
}
