[package]
name = "bigospice-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SPICE/Spectre netlist parser for BigOSpice"

[dependencies]
bigospice-core.workspace = true
bigospice-utility.workspace = true
thiserror.workspace = true
ahash.workspace = true
smallvec.workspace = true
log.workspace = true
phf.workspace = true

[dev-dependencies]
tempfile.workspace = true
