pub(crate) mod result;
pub(crate) mod companion;
pub(crate) mod dc_op;
pub(crate) mod dc_sweep;
pub(crate) mod transient;
pub(crate) mod ac;
pub mod measure;
pub(crate) mod fourier;
pub(crate) mod sensitivity;
pub(crate) mod noise;
pub mod hb;
pub(crate) mod tf;
pub(crate) mod pz;
pub(crate) mod sens_ac;
pub(crate) mod disto;
pub(crate) mod fft;
pub(crate) mod mc;
pub(crate) mod wcase;
pub mod sweep;
pub mod sp;
pub(crate) mod alter;
pub mod control;
pub(crate) mod pss;
pub(crate) mod envelope;
pub(crate) mod sampling;
pub(crate) mod rol;

pub use result::{SimResult, ResultData, DcOpResult, DcSweepResult, TransientResult, AcResult};
pub use companion::{CompanionMethod, assemble_be_jacobian, assemble_be_residual, assemble_gear2_residual};
pub use dc_op::{run_dc_op, run_dc_op_with_config, run_dc_op_with_options, DcOpOutput,
                run_nested_dc, run_nested_dc_with_options, NestedDcConfig, NestedDcResult};
pub use dc_sweep::{run_dc_sweep, run_dc_sweep_with_options, DcSweepConfig};
pub use transient::{run_transient, run_transient_with_options, TransientConfig, IntegrationMethod};
pub use ac::{run_ac, run_ac_with_options, AcConfig, AcSweepType};
pub use fourier::{run_fourier, run_fft as run_fourier_fft, FourierConfig, FourierResult, FourierSignal, FourierHarmonic};
pub use sensitivity::{run_sens_dc, run_sens_dc_with_options, SensConfig, SensOutput, SensEntry, SensResult};
pub use noise::{NoiseConfig, NoiseResult, DeviceNoiseContribution, run_noise, run_noise_with_options};
pub use tf::{run_tf, run_tf_with_options, TfConfig, TfResult};
pub use pz::{run_pz, run_pz_with_options, PzConfig, PzResult, Complex as PzComplex};
pub use sens_ac::{run_sens_ac, run_sens_ac_with_options, SensAcConfig, SensAcOutput, SensAcEntry, SensAcResult};
pub use disto::{run_disto, run_disto_with_options, DistoConfig, DistoResult};
pub use fft::{run_fft, FftConfig, FftWindow, FftResult};
pub use mc::{run_mc, McConfig, McSampleResults, StatOverride};
pub use wcase::{run_wcase, WcaseConfig, WcaseCorner, WcaseResults};
pub use pss::{run_pss, PssConfig, PssResult, ErrPreset};
pub use envelope::{run_envelope, EnvelopeConfig, EnvelopeResult};
pub use sampling::{run_sampling, summarise, SamplingConfig, SamplingStrategy, SamplingSummary};
pub use hb::{run_hb_n_tone, HbNToneConfig, HbResult, OsdiHbDevice};
pub use rol::{run_rol, RolConfig, RolResult, DeviceDegradation};
pub use alter::{AlterBlock, AlterParam, run_alter};
pub use sweep::{ParamSweep, ParamTarget};
