pub(crate) mod stamper;
pub(crate) mod convergence;
pub(crate) mod damping;
pub(crate) mod source_stepping;
pub(crate) mod gmin_stepping;
pub(crate) mod junction_limit;
pub(crate) mod newton;
pub(crate) mod backend;
pub(crate) mod anderson;
pub(crate) mod pseudo_transient;
pub(crate) mod device_eval;

pub use stamper::{stamp_circuit, stamp_circuit_into, stamp_circuit_gc_into, stamp_circuit_gc_at_time, stamp_circuit_gc_par_at_time, stamp_circuit_with_source_scale, update_tline_histories, update_ltra_histories};
pub use convergence::{ConvergenceCriteria, ConvergenceStatus};
pub use damping::DampingStrategy;
pub use source_stepping::SourceStepping;
pub use gmin_stepping::GminStepping;
pub use newton::{NewtonRaphson, NrConfig, NrResult, DEFAULT_GPU_DEVICE_THRESHOLD};
pub use backend::{Solver, SolverConfig, SolverKind};
pub use anderson::AndersonAcceleration;
pub use pseudo_transient::{PseudoTransientConfig, solve_pseudo_transient};
pub use device_eval::{eval_bsim4_batch, should_use_gpu};
