[package]
name = "incspice-core"
edition.workspace = true
version.workspace = true

[dependencies]
ahash       = { workspace = true }
serde       = { workspace = true }
smallvec    = { workspace = true }
thiserror   = { workspace = true }
slotmap     = { workspace = true }
compact_str = { workspace = true }
fixedbitset = { workspace = true }
arrayvec    = { workspace = true }
