//! vagen: build-time Verilog-A / Verilog → contract-shaped Zig device modules.
//!
//! Usage: vagen <out_dir> <file.va|file.v>...
//!
//! Writes <name>.zig per input plus va_root.zig re-exporting each device, so
//! the engine's comptime registry and the GPU megakernel dispatch see the
//! same `va_devices` module. Runs as a build step (-Dva-models=<dir>); the
//! runtime dlopen path is gone — a model missing here is a build-time gap,
//! not a silent CPU fallback.

const std = @import("std");
const fastvaf = @import("fastvaf");

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len < 3) {
        std.debug.print("usage: vagen <out_dir> <file.va|file.v>...\n", .{});
        return error.BadUsage;
    }
    const out_dir = args[1];

    var root: std.ArrayList(u8) = .empty;
    try root.appendSlice(arena, "//! Generated by vagen — Verilog-A/Verilog devices, contract-shaped.\n");

    for (args[2..]) |path| {
        const source = try std.Io.Dir.cwd().readFileAlloc(io, path, arena, .limited(64 * 1024 * 1024));
        var name: []const u8 = undefined;
        var zig_source: []const u8 = undefined;

        if (std.mem.endsWith(u8, path, ".va")) {
            var result = fastvaf.compileSource(arena, source, null) catch |err| {
                std.debug.print("vagen: {s}: Verilog-A compile failed: {s}\n", .{ path, @errorName(err) });
                return err;
            };
            zig_source = fastvaf.va.codegen.generate(arena, &result.mir, &result.lower) catch |err| {
                std.debug.print("vagen: {s}: codegen failed: {s}\n", .{ path, @errorName(err) });
                return err;
            };
            name = try arena.dupe(u8, result.mir.name);
        } else if (std.mem.endsWith(u8, path, ".v") or std.mem.endsWith(u8, path, ".sv")) {
            zig_source = fastvaf.fromVerilog(arena, io, source) catch |err| {
                std.debug.print("vagen: {s}: Verilog codegen failed: {s}\n", .{ path, @errorName(err) });
                return err;
            };
            name = moduleName(source) orelse std.fs.path.stem(path);
        } else {
            std.debug.print("vagen: {s}: expected .va/.v/.sv\n", .{path});
            return error.BadUsage;
        }

        try std.Io.Dir.cwd().writeFile(io, .{
            .sub_path = try std.fs.path.join(arena, &.{ out_dir, try std.fmt.allocPrint(arena, "{s}.zig", .{name}) }),
            .data = zig_source,
        });
        try root.appendSlice(arena, try std.fmt.allocPrint(
            arena,
            "pub const @\"{s}\" = @import(\"{s}.zig\");\n",
            .{ name, name },
        ));
    }

    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = try std.fs.path.join(arena, &.{ out_dir, "va_root.zig" }),
        .data = root.items,
    });
}

/// `module NAME (...)` — first module wins (matches the old runtime parse).
fn moduleName(source: []const u8) ?[]const u8 {
    const mod_start = std.mem.indexOf(u8, source, "module ") orelse return null;
    const paren = std.mem.indexOfPos(u8, source, mod_start, "(") orelse return null;
    const name = std.mem.trim(u8, source[mod_start + 7 .. paren], " \t\n\r");
    return if (name.len > 0) name else null;
}
